# Generated by Django 4.2.11 on 2024-05-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0003_rename_content_message_message_message_room_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prouser',
            managers=[
            ],
        ),
    ]
